name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: {{#dependencies}}
  {{package}}: {{version}}{{/dependencies}}

dev_dependencies: {{#dev_dependencies}}
  {{package}}: {{version}}{{/dev_dependencies}}
