import 'package:core_aggregate/core_aggregate.dart';
import 'package:core_application/core_application.dart';

abstract interface class CorePackageBehavior<
        PackageAdapter extends CorePackageAdapter<
            PackageView,
            PackageRequest,
            CollectionAdapter,
            CollectionView,
            CollectionRequest,
            EntityAdapter,
            EntityView,
            EntityRequest,
            EntityRef>,
        PackageHandle extends CorePackageHandle<
            PackageRequest,
            PackageEvent,
            PackageState,
            CollectionHandle,
            CollectionRequest,
            CollectionEvent,
            CollectionState,
            EntityHandle,
            EntityRequest,
            EntityEvent,
            EntityState,
            EntityRef>,
        PackageView extends CorePackageView<CollectionView, EntityView, EntityRef>,
        PackageRequest extends CorePackageRequest<CollectionRequest, EntityRequest,
            EntityRef>,
        PackageEvent extends CorePackageEvent<CollectionEvent, EntityEvent, EntityRef>,
        PackageState extends CorePackageState<CollectionState, EntityState, EntityRef>,
        CollectionAdapter extends CoreCollectionAdapter<CollectionView,
            CollectionRequest, EntityAdapter, EntityView, EntityRequest, EntityRef>,
        CollectionHandle extends CoreCollectionHandle<
            CollectionRequest,
            CollectionEvent,
            CollectionState,
            EntityHandle,
            EntityRequest,
            EntityEvent,
            EntityState,
            EntityRef>,
        CollectionView extends CoreCollectionView<EntityView, EntityRef>,
        CollectionRequest extends CoreCollectionRequest<EntityRequest, EntityRef>,
        CollectionEvent extends CoreCollectionEvent<EntityEvent, EntityRef>,
        CollectionState extends CoreCollectionState<EntityState, EntityRef>,
        EntityHandle extends CoreEntityHandle<EntityRequest, EntityEvent,
            EntityState>,
        EntityAdapter extends CoreEntityAdapter<EntityView, EntityRequest>,
        EntityRequest extends CoreEntityRequest,
        EntityEvent extends CoreEntityEvent,
        EntityState extends CoreEntityState,
        EntityView extends CoreEntityView,
        EntityRef extends CoreEntityRef>
    implements
        EventSourcedBehavior<PackageAdapter, PackageHandle, PackageView, PackageRequest,
            PackageEvent, PackageState> {}
