name: core_aggregate_analyzer
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-91.0.dev

dependencies:
  antlr4:
  belatuk_code_buffer:
  belatuk_symbol_table:
  build:
  built_value:
  built_collection:
  code_builder:
  collection:
  core_protoc:
  path:
  protobuf:
  protoc_plugin:
  protoc_plugin_support:

dev_dependencies:
  build_runner:
  built_value_generator:
  built_value_test:
  core_analysis:
  mocktail: ^1.0.0
  test:
