name: core_protoc
description: Toolkit to develop protoc-gen plugins
version: 0.1.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path:
  protobuf:
  protocolbuffers_wellknowntypes:
  protoc_plugin:

dev_dependencies:
  mocktail: ^1.0.0
  test:
  core_analysis: 
