name: flakka

ide:
  intellij:
    moduleNamePrefix: ''
packages:
  - packages/**
#ignore:
#  - packages/core_aggregate/core_aggregate_api/test/**
command:
  bootstrap:
    dependencyOverridePaths:
      - ../core_sdk/packages/**
