name: Calculator

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/calculator_verify_and_test.yaml"
      - "integration/development/calculator/**"

  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "integration/development/calculator/**"


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main
    with:
      working_directory: integration/development/calculator
      dart_sdk: stable
      min_coverage: 140
