name: Integration Test Runner

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/integration_test_runner_verify_and_test.yaml"
      - "integration/integration_test_runner/**"

  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "integration/integration_test_runner/**"


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@main
    with:
      working_directory: integration/integration_test_runner
      min_coverage: 140
      flutter_channel: stable
      flutter_version: stable
